name: Golang lint and test
on: push
jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: go1.14 lint
        run: |
          # https://github.com/golang/lint
          go get -u golang.org/x/lint/golint
          make lint