name: k8gb-plugin build
on:
  push:
    branches-ignore:
      - release
  pull_request:
    branches:
      - master

jobs:
  k8gb-plugin-build:
    name: k8gb-plugin build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.2.0
        with:
          args: ./...
      - name: go1.14 linters
        uses: AbsaOSS/golang-pipeline/go1.14/linter@master
      - name: go1.14 tests
        uses: AbsaOSS/golang-pipeline/go1.14/test@master
