name: Golang lint and test
on: push
jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: go1.14 linters
        uses: AbsaOSS/golang-pipeline/go1.14/linter@master
#        with:
#          GOLINT: on
      - name: go1.14 test
        uses: AbsaOSS/golang-pipeline/go1.14/test@master
