name: k8gb-plugin release
on:
  release:
    types: [published]

jobs:
  my-test:
    runs-on: self-hosted
    #env:
    #...
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: |
          make pre-push

  k8gb-plugin-release:
    name: k8gb-plugin release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.2.0
        with:
          args: ./...

      - name: go1.14 linters
        uses: AbsaOSS/golang-pipeline/go1.14/linter@master

      - name: go1.14 tests
        uses: AbsaOSS/golang-pipeline/go1.14/test@master

      - name: go1.14 release linux
        uses: kuritka/golang-pipeline/go1.14/release@master
        env:
          #when path is different from root
          #PROJECT_PATH: "./cmd/manager"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOS: linux
          GOARCH: amd64
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
